name: transactions-app

version: "3.8"

services:
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/transactions_db
    networks:
      - transactions-app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - transactions-app
    depends_on:
      - mongo
volumes:
  mongo_data:
networks:
  transactions-app:
    driver: bridge
