name: transactions-app

version: "3.8"

services:
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/transactions_db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - transactions-app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - transactions-app
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file: ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - transactions-app
    ports:
      - 5173:5173
    depends_on:
      - backend
volumes:
  mongo_data:
networks:
  transactions-app:
    driver: bridge
